config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "tweets#index"
  resources :tweets, only:[:new,:create,:index, :show, :destroy, :edit] do
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow,class_name: 'User'


  with_options presence: true do
  validates :user_id
  validates :follow_id
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  with_options presence: true do
    validates :play
    validates :description
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :tweets
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         with_options presence: true do
          validates :nickname
          validates :myinfo
          validates :password, format: { with:/\A[a-zA-Z0-9]+\z/}
          validates :password, length: { maximum: 12}
         end


         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :myinfo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id] )
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      redirect_to root_path
    end
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:image, :description,:play).merge(user_id: current_user.id)
  end
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:edit]
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.includes(:user)
  end

  def edit
    user = User.find(params[:id])
    unless current_user.id == user.id
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def user_params
    params.permit(:nickname, :myinfo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </li>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>yumecoot</title>
    <meta name="descripton" content="夢の語り場所。自身の夢の投稿！人の夢を応援！">
    <meta charset= "UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "/user/registrations", :media => "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel= "stylesheet" href="stylesheets/rest.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="item">
  <%if @tweets.length !=0 %>
      <%= link_to tweet_path(tweet), method: :get do %>
        <div class="description">
          <%= tweet.description %>
        </div>
        <div class="play">
          <%= tweet.play %>
        </div>
      <% end %>
        <%= image_tag tweet.image.variant( resize: '300x300'),class: "image" if tweet.image.attached? %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="wrap">
  <div class="side-bar">
    <% if user_signed_in? %>
      <div class="myname"><%= current_user.nickname %></div>
    <div><%= link_to 'ログアウト',destroy_user_session_path, method: :delete,    class:"logout"%></div>
    <div><%= link_to 'マイページ',user_path(current_user.id), method: :get, class:"mypage"%></div>
    <% else %>
    <div><%= link_to 'ログイン', new_user_session_path , class:"login" %></div>
    <div><%= link_to '新規登録',new_user_registration_path, class:"sign-up"%></div>
    <% end %>
    <div><%= link_to '投稿',  new_tweet_path, class:"tweet-up"%></div>
  </div>
  <div class="main-contents">
    <%if @tweets.length !=0 %>
      <% @tweets.each do |tweet| %>
        <%= link_to tweet_path(tweet), method: :get do %>
          <div class="description">
            <%= tweet.description %>
          </div>
            <div class="play">
              <%= tweet.play %>
            </div>
            <%= image_tag tweet.image.variant( resize: '300x300'),class: "image" if tweet.image.attached? %>
          <% end %>
      <% end %>
    <% else %>
     <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ１" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test.jpg",  size: '300x300' , class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ2" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test2.jpg", size: '300x300', class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ3" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test3.jpg", size: '300x300', class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ4" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test4.jpg", size: '300x300', class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ5" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test5.jpg", size: '300x300', class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ6" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test6.jpg", size: '300x300', class: "image" %>
        <% end %>
         <%= link_to '#' do %>
          <div class="description">
            <%= "ダミーデータ１" %>
          </div>
            <div class="play">
              <%= "これはダミー投稿です。" %>
            </div>
            <%= image_tag "test.jpg", size: '300x300', class: "image" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="tweet-wrap">
  <h2>投稿画面</h2>
  <%= form_with model:@tweet,local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    <div class="tweet-group">
      <%= f.text_field :description, class:"tweet-description", id:"tweet-info", placeholder:"叶えたい夢のタイトル" %>
    </div>
    <div class="tweet-group">
      <div class="tweet-play">
        <%= f.text_area :play, class:"tweet-text", id:"tweet-info", placeholder:"行動した事これからする事！"%>
      </div>
    </div>
    <div class="tweet-group">
      <p>
        勉強、練習などの写真、スクリーンショットなどをあげよう
      </p>
    </div>
    <div class="tweet-group">
      <div class="tweet-img">
        <%= f.file_field :image, id:"tweet-imag"%>
      </div>
    </div>
    <div class="tweet-btn-content">
      <%= f.submit "投稿する", class:"tweet-btn"%>
    </div>
    <div class="bacl-btn">
      <%= link_to '戻る', root_path, class:"back-btn-b"%>
  <% end %> 
</div>

app/views/tweets/show.html.erb
<div class="show-group">
  <div class="show-wrap">
      <h2>詳細ページ</h2>
  </div>
  <div class="show-wrap">
    <div class="show_name">
      <%=link_to "投稿者 #{ @tweet.user.nickname}",user_path(@tweet.user_id) , method: :get , class: :show_name%>
    </div>
  </div>
  <div class="show-wrap">
    <div class="show-description">
    <h4>
    タイトル
    </h4>
      <%= @tweet.description%>
    </div>
  </div>
  <div class="show-wrap">
    <div class="show-play">
    <h4>
    行動
    </h4>
      <%= @tweet.play%>
    </div>
  </div>
  <div class="show-wrap">
    <div class="show-img">
      <%= image_tag @tweet.image.variant( resize: '500x500') ,class:"show-image" if @tweet.image.attached? %>
    </div>
  </div>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, class: :com_text,placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <h6>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</h6>
    <% end %>
        <div class="comments">
      <h5>＜コメント一覧＞</h5>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="show-wrap">
    <div>
    <%= link_to "削除", tweet_path(@tweet), method: :delete, class: :tweet_delete %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="edit-group">
  <h2>編集ページ</h2>

  <%= form_with model: @user, url: user_path, method: :patch, class: 'update-main', local: true do |f|%>
  <div class="from-wrap">
    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">ニックネーム</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :nickname, class:"input-name", id:"nickname", placeholder:"例）タロウ（TARO）"%>
    </div>
    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">自己紹介文</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :myinfo, class:"input-default", id:"myinfo", placeholder:"例）私はITエンジニアを目指しています。某プログラミングサイトで独学で学んでいます。"%>
    </div>
    <div class="register-btn">
      <%= f.submit "更新", class:"register-red-btn"%>
    </div>
    <div class="back-btn">
      <%= link_to '戻る', root_path, class:"back-btn-singup"%>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="op">
    <%= link_to '編集',  edit_user_path(@user.id), method: :get, class: "edit"%>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
  <div class="inner">
    <div class="user__wrapper">
      <div class="myinfos">
        <div class="myinfo">
          <h2 class="page-heading">
            <%= @user.nickname%>さんの情報
          </h2>
          <div class="main-table">
            <table class="table" >
              <tr>
                <th class="table-col1">名前</th>
                <td class="table-col2"><%= @user.nickname%></td>
                </tr>
                <tr>
                <th class="table-col1">プロフィール</th>
                <td class="table-col2"><%= @user.myinfo%></td>
              </tr>
            </table>
          </div>
            <h2 class="page-heading">
              <%= "#{@user.nickname}さんの投稿"%>
            </h2>
        </div>
      </div>
        <div class="mytweet">
          <%= render partial: 'tweets/tweet',collection: @tweets %>
        </div>
    </div>
  </div>
</div>